# Generated by Django 3.2.8 on 2022-01-15 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(max_length=50)),
                ('title', models.TextField(default='')),
                ('authors', models.TextField(default='')),
                ('abstract', models.TextField(default='')),
                ('term', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=250)),
                ('vectorized', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(choices=[('Algorithms', 'Algorithms'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Networking', 'Networking'), ('Wireless Communication', 'Wireless Communication'), ('Data Science', 'Data Science'), ('Molecular Communication', 'Molecular Communication'), ('Computer Science', 'Computer Science')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150)),
                ('hashId', models.CharField(max_length=300)),
                ('confirmation', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('state', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='reader_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readers', models.EmailField(max_length=150)),
                ('keywords', models.ManyToManyField(blank=True, to='suggestapp.keyword')),
            ],
        ),
    ]
