# Generated by Django 3.2.8 on 2022-01-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0002_retrieveSave'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader', models.EmailField(max_length=150)),
                ('doi', models.CharField(max_length=50)),
                ('term', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=150)),
            ],
        ),
    ]
