# Generated by Django 3.2.8 on 2022-01-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestapp', '0005_alter_article_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_name',
            field=models.CharField(choices=[('Algorithms', 'Algorithms'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Networking', 'Networking'), ('Wireless Communication', 'Wireless Communication'), ('Data Science', 'Data Science'), ('Molecular Communication', 'Molecular Communication'), ('Computer Science', 'Computer Science')], max_length=100, null=True, unique=True),
        ),
    ]
